apiVersion: v1
kind: Service
metadata:
  name: linkshort-service
  namespace: linkshort
spec:
  selector:
    app: linkshort
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkshort
spec:
  selector:
    matchLabels:
      app: linkshort
  replicas: 5
  template:
    metadata:
      labels:
        app: linkshort
    spec:
      containers:
      - name: linkshort
        image: docker.io/jackseceng/linkshort:beta
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_PASSWORD
          value: b3stp@$$w0rd # Obviously not for prd
        - name: REDIS_USERNAME
          value: default # Obviously not for prd

# kubectl create ns linkshort
# kubectl apply -n linkshort -f .\src\app-deployment.yaml
# kubectl get po -n linkshort 
# kubectl get svc -n linkshort
# minikube service -n linkshort linkshort-app-service

# To delete:
# kubectl delete deployment linkshort -n linkshort
