---
name: Trivy Scan

on:
  workflow_run:
    workflows: ["Build Container Image"]
    types:
      - completed

env:
  REGISTRY: docker.io
  REPOSITORY: jackseceng
  IMAGE_NAME: linkshort

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    # Run scan only if the triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      security-events: write

    steps:
      -
        name: 'Get image tag'
        id: get_tag
        run: |
          if [[ "${{ github.event.workflow_run.event }}" == "pull_request" ]]; then
            echo "tag=${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.tag }}'
          scan-type: 'image'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'sarif'
          output: 'trivy-results.sarif'

      -
        name: Upload Trivy results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@e296a935590eb16afc0c0108289f68c87e2a89a5 # v4.30.7
        with:
          sarif_file: 'trivy-results.sarif'
